### PR TITLE
Fix #9 Inject service manager via factory

### LINKED ISSUE #9: Got call to undefined method error
I tried to install HtUserRegistration but I got the following error:

`Fatal error: Call to undefined method HtUserRegistration\Service\UserRegistrationService::getServiceLocator() in C:\xampp\htdocs\vendor\hrevert\ht-user-registration\src\Service\UserRegistrationService.php on line 79`

Is this a bug or have I made a mistake during the installation?

### PR DESCRIPTION
**Pull request by fabwu**

### CODE REVIEW

**Comment by ojhaujjwal** [comment]
Please inject the mailer service and don't inject service manager!

**Comment by ojhaujjwal** [comment]
@wuethrich44 Tests are fine. Did you test it manually too?

**Comment by ojhaujjwal** [comment]
May I tag 0.0.1 if it is working?

**Comment by fabwu** [comment]
You should merge #4 because I got this error too...

**Comment by fabwu** [comment]
See also #11

**Pull request merged**
